
package Aplicacao;

public enum TiposDeFontesDeFosforo {
    SUPERFOSFATO_SIMPLES,
    SUPERFOSFATO_TRIPLO,
    MAP,
    DAP,
    YOORIN,
    FOSFATO_ARAD,
    FOSFATO_GAFSA,
    FOSFATO_DAOUI,
    FOSFATO_PATOS_MINAS,
    ESCORIA_DE_THOMAS,
    ACIDO_FOSFORICO,
    MULTIF_MAGNESIANO;
}
